# Generated by Django 6.0 on 2025-12-17 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alternate_name', models.CharField(blank=True, max_length=100)),
                ('mobile_primary', models.CharField(max_length=10, unique=True)),
                ('mobile_secondary', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('profession', models.CharField(max_length=100)),
                ('nominee_name', models.CharField(max_length=100)),
                ('nominee_mobile', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='customers/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('carat', models.IntegerField(choices=[(18, '18K'), (20, '20K'), (22, '22K'), (24, '24K')])),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('approved_net_weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoldItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gold_items/images/')),
                ('gold_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gold_loan.golditem')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=20, unique=True)),
                ('loan_number', models.CharField(max_length=20, unique=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=8)),
                ('approved_grams', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='gold_loan.customer')),
            ],
        ),
        migrations.AddField(
            model_name='golditem',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gold_loan.loan'),
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('photo', 'Photo'), ('other', 'Other')], max_length=20)),
                ('other_name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='loan_documents/')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gold_loan.loan')),
            ],
        ),
    ]
