# Generated by Django 6.0 on 2025-12-17 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='alternate_name',
        ),
    ]
